DROP TABLE if exists IDS CASCADE;
CREATE TABLE IDS  (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);


DROP TABLE LETTCCMMNCLCODE CASCADE;
CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM char(60) ,
  CL_CODE_DC char(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;


DROP TABLE LETTCCMMNCODE CASCADE;
CREATE TABLE LETTCCMMNCODE  (
  CODE_ID char(6) NOT NULL,
  CODE_ID_NM char(60) ,
  CODE_ID_DC char(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;


DROP TABLE LETTCCMMNDETAILCODE CASCADE;
CREATE TABLE LETTCCMMNDETAILCODE  (
  CODE_ID char(6) NOT NULL,
  CODE char(15) NOT NULL,
  CODE_NM char(60) ,
  CODE_DC char(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;


DROP TABLE LETTNORGNZTINFO CASCADE;
CREATE TABLE LETTNORGNZTINFO  (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM char(20) NOT NULL,
  ORGNZT_DC char(100) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;


DROP TABLE LETTNAUTHORGROUPINFO CASCADE;
CREATE TABLE LETTNAUTHORGROUPINFO  (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM char(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC char(100) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;


DROP TABLE LETTNEMPLYRINFO CASCADE;
CREATE TABLE LETTNEMPLYRINFO  (
  EMPLYR_ID char(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM char(60) NOT NULL,
  PASSWORD char(200) NOT NULL,
  EMPL_NO char(20) ,
  IHIDNUM char(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM char(20) ,
  HOUSE_ADRES char(100) ,
  PASSWORD_HINT char(100) NOT NULL,
  PASSWORD_CNSR char(100) NOT NULL,
  HOUSE_END_TELNO char(4) ,
  AREA_NO char(4) ,
  DETAIL_ADRES char(100) ,
  ZIP char(6) ,
  OFFM_TELNO char(20) ,
  MBTLNUM char(20) ,
  EMAIL_ADRES char(50) ,
  OFCPS_NM char(60) ,
  HOUSE_MIDDLE_TELNO char(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE char(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE char(20) ,
  SBSCRB_DE DATE ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;


DROP TABLE LETTNTMPLATINFO CASCADE;
CREATE TABLE LETTNTMPLATINFO  (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM char(255) ,
  TMPLAT_COURS char(2000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID char(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT LETTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;


DROP TABLE LETTNBBSMASTER CASCADE;
CREATE TABLE LETTNBBSMASTER  (
  BBS_ID char(20) NOT NULL,
  BBS_NM char(255) NOT NULL,
  BBS_INTRCN char(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID char(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;


DROP TABLE LETTNBBSUSE CASCADE;
CREATE TABLE LETTNBBSUSE  (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID char(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;


DROP TABLE LETTNBBS CASCADE;
CREATE TABLE LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ char(2000) ,
  NTT_CN bytea,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(11) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID char(20) ,
  NTCR_NM char(20) ,
  PASSWORD char(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID char(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;


DROP TABLE LETTNBBSMASTEROPTN CASCADE;
CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT current_date NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  FRST_REGISTER_ID char(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID char(20) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;


DROP TABLE LETTNENTRPRSMBER CASCADE;
CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID char(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO char(10) ,
  JURIRNO char(13) ,
  CMPNY_NM char(60) NOT NULL,
  CXFC char(50) ,
  ZIP char(6) ,
  ADRES char(100) ,
  ENTRPRS_MIDDLE_TELNO char(4) ,
  FXNUM char(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM char(50) NOT NULL,
  APPLCNT_IHIDNUM char(200) ,
  SBSCRB_DE DATE ,
  ENTRPRS_MBER_STTUS char(15) ,
  ENTRPRS_MBER_PASSWORD char(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT char(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR char(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES char(100) ,
  ENTRPRS_END_TELNO char(4) ,
  AREA_NO char(4) ,
  APPLCNT_EMAIL_ADRES char(50) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;


DROP TABLE LETTNFILE CASCADE;
CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;


DROP TABLE LETTNFILEDETAIL CASCADE;
CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS char(2000) NOT NULL,
  STRE_FILE_NM char(255) NOT NULL,
  ORIGNL_FILE_NM char(255) ,
  FILE_EXTSN char(20) NOT NULL,
  FILE_CN bytea,
  FILE_SIZE numeric(8,0) ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;


DROP TABLE LETTNGNRLMBER CASCADE;
CREATE TABLE LETTNGNRLMBER (
  MBER_ID char(20) DEFAULT '' NOT NULL,
  PASSWORD char(200) NOT NULL,
  PASSWORD_HINT char(100) NOT NULL,
  PASSWORD_CNSR char(100) NOT NULL,
  IHIDNUM char(200) ,
  MBER_NM char(50) NOT NULL,
  ZIP char(6) ,
  ADRES char(100) ,
  AREA_NO char(4) ,
  MBER_STTUS char(15) ,
  DETAIL_ADRES char(100) ,
  END_TELNO char(4) ,
  MBTLNUM char(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM char(20) ,
  MBER_EMAIL_ADRES char(50) ,
  MIDDLE_TELNO char(4) ,
  SBSCRB_DE DATE ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;


DROP TABLE LETTNSCHDULINFO CASCADE;
CREATE TABLE LETTNSCHDULINFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID char(20) ,
  SCHDUL_KND_CODE char(20) ,
  SCHDUL_BEGINDE char(20) ,
  SCHDUL_ENDDE char(20) ,
  SCHDUL_NM char(255) ,
  SCHDUL_CN char(2500) ,
  SCHDUL_PLACE char(255) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID char(20) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID char(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID char(20) ,
  REPTIT_SE_CODE char(3) ,
  CONSTRAINT LETTNSCHDULINFO_PK PRIMARY KEY (SCHDUL_ID)
) ;


CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;